python pyang.py -f callbackreg /home/guoliang/Desktop/WorkSpace/CertusNet/oam_du/5gran/radisys-du/src/du_app/oam_agent/yang_model/gnb/dev/certus-5gnr-du-devicebaseinfo.yang -p /home/guoliang/Desktop/WorkSpace/CertusNet/oam_du/5gran/radisys-du/src/du_app/oam_agent/yang_model/gnb/comm -o /home/guoliang/Desktop/WorkSpace/CertusNet/oam_du/5gran/radisys-du/src/du_app/oam_agent/yang_model/gnb/ref/reg1.cpp
python pyang.py -f pathheader /home/guoliang/Desktop/WorkSpace/CertusNet/oam_du/5gran/radisys-du/src/du_app/oam_agent/yang_model/gnb/dev/certus-5gnr-du-devicebaseinfo.yang -p /home/guoliang/Desktop/WorkSpace/CertusNet/oam_du/5gran/radisys-du/src/du_app/oam_agent/yang_model/gnb/comm -o /home/guoliang/Desktop/WorkSpace/CertusNet/oam_du/5gran/radisys-du/src/du_app/oam_agent/yang_model/gnb/ref/header1.h


python pyang.py -f callbackreg /home/guoliang/Desktop/WorkSpace/CertusNet/oam_du/5gran/radisys-du/src/du_app/oam_agent/yang_model/gnb/cell/certus-5gnr-du-cell-cfg.yang -p /home/guoliang/Desktop/WorkSpace/CertusNet/oam_du/5gran/radisys-du/src/du_app/oam_agent/yang_model/gnb/comm -o /home/guoliang/Desktop/WorkSpace/CertusNet/oam_du/5gran/radisys-du/src/du_app/oam_agent/yang_model/gnb/ref/reg2.cpp
python pyang.py -f pathheader /home/guoliang/Desktop/WorkSpace/CertusNet/oam_du/5gran/radisys-du/src/du_app/oam_agent/yang_model/gnb/cell/certus-5gnr-du-cell-cfg.yang -p /home/guoliang/Desktop/WorkSpace/CertusNet/oam_du/5gran/radisys-du/src/du_app/oam_agent/yang_model/gnb/comm -o /home/guoliang/Desktop/WorkSpace/CertusNet/oam_du/5gran/radisys-du/src/du_app/oam_agent/yang_model/gnb/ref/header2.h

python pyang.py -f callbackreg /home/guoliang/Desktop/WorkSpace/CertusNet/oam_du/5gran/radisys-du/src/du_app/oam_agent/yang_model/gnb/alm/certus-5gnr-alarms.yang -p /home/guoliang/Desktop/WorkSpace/CertusNet/oam_du/5gran/radisys-du/src/du_app/oam_agent/yang_model/gnb/comm -o /home/guoliang/Desktop/WorkSpace/CertusNet/oam_du/5gran/radisys-du/src/du_app/oam_agent/yang_model/gnb/ref/reg3.cpp
python pyang.py -f pathheader /home/guoliang/Desktop/WorkSpace/CertusNet/oam_du/5gran/radisys-du/src/du_app/oam_agent/yang_model/gnb/alm/certus-5gnr-alarms.yang -p /home/guoliang/Desktop/WorkSpace/CertusNet/oam_du/5gran/radisys-du/src/du_app/oam_agent/yang_model/gnb/comm -o /home/guoliang/Desktop/WorkSpace/CertusNet/oam_du/5gran/radisys-du/src/du_app/oam_agent/yang_model/gnb/ref/header3.h
