#python pyang.py -f callbackreg /home/guoliang/Desktop/WorkSpace/CertusNet/oam_du/5gran/radisys-du/src/du_app/oam_agent/yang_model/gnb/dev/certus-5gnr-du-devicebaseinfo.yang -p /home/guoliang/Desktop/WorkSpace/CertusNet/oam_du/5gran/radisys-du/src/du_app/oam_agent/yang_model/gnb/comm -o /home/guoliang/Desktop/WorkSpace/CertusNet/oam_du/5gran/radisys-du/src/du_app/oam_agent/yang_model/gnb/ref/reg1.cpp
#python pyang.py -f pathheader /home/guoliang/Desktop/WorkSpace/CertusNet/oam_du/5gran/radisys-du/src/du_app/oam_agent/yang_model/gnb/dev/certus-5gnr-du-devicebaseinfo.yang -p /home/guoliang/Desktop/WorkSpace/CertusNet/oam_du/5gran/radisys-du/src/du_app/oam_agent/yang_model/gnb/comm -o /home/guoliang/Desktop/WorkSpace/CertusNet/oam_du/5gran/radisys-du/src/du_app/oam_agent/yang_model/gnb/ref/header1.h

#python pyang.py -f callbackreg /home/guoliang/Desktop/WorkSpace/CertusNet/oam_du/5gran/radisys-du/src/du_app/oam_agent/yang_model/gnb/cell/certus-5gnr-du-cell-cfg.yang -p /home/guoliang/Desktop/WorkSpace/CertusNet/oam_du/5gran/radisys-du/src/du_app/oam_agent/yang_model/gnb/comm -o /home/guoliang/Desktop/WorkSpace/CertusNet/oam_du/5gran/radisys-du/src/du_app/oam_agent/yang_model/gnb/ref/reg2.cpp
#python pyang.py -f pathheader /home/guoliang/Desktop/WorkSpace/CertusNet/oam_du/5gran/radisys-du/src/du_app/oam_agent/yang_model/gnb/cell/certus-5gnr-du-cell-cfg.yang -p /home/guoliang/Desktop/WorkSpace/CertusNet/oam_du/5gran/radisys-du/src/du_app/oam_agent/yang_model/gnb/comm -o /home/guoliang/Desktop/WorkSpace/CertusNet/oam_du/5gran/radisys-du/src/du_app/oam_agent/yang_model/gnb/ref/header2.h

#python pyang.py -f callbackreg /home/guoliang/Desktop/WorkSpace/CertusNet/oam_du/5gran/radisys-du/src/du_app/oam_agent/yang_model/gnb/alm/certus-5gnr-alarms.yang -p /home/guoliang/Desktop/WorkSpace/CertusNet/oam_du/5gran/radisys-du/src/du_app/oam_agent/yang_model/gnb/comm -o /home/guoliang/Desktop/WorkSpace/CertusNet/oam_du/5gran/radisys-du/src/du_app/oam_agent/yang_model/gnb/ref/reg3.cpp
#python pyang.py -f pathheader /home/guoliang/Desktop/WorkSpace/CertusNet/oam_du/5gran/radisys-du/src/du_app/oam_agent/yang_model/gnb/alm/certus-5gnr-alarms.yang -p /home/guoliang/Desktop/WorkSpace/CertusNet/oam_du/5gran/radisys-du/src/du_app/oam_agent/yang_model/gnb/comm -o /home/guoliang/Desktop/WorkSpace/CertusNet/oam_du/5gran/radisys-du/src/du_app/oam_agent/yang_model/gnb/ref/header3.h


#python pyang.py -f tree /home/guoliang/Desktop/WorkSpace/CertusNet/oam_du/5gran/radisys-du/src/du_app/oam_agent/yang/cell/certus-5gnr-du-cells@2019-06-20.yang -p /home/guoliang/Desktop/WorkSpace/CertusNet/oam_du/5gran/radisys-du/src/du_app/oam_agent/yang/cell -p /usr/local/confd/src/confd/yang -o ~/Desktop/WorkSpace/111.tree
#python pyang.py -f jsonxsl /home/guoliang/Desktop/WorkSpace/CertusNet/oam_du/5gran/radisys-du/src/du_app/oam_agent/yang/cell/certus-5gnr-du-cells@2019-06-20.yang -p /home/guoliang/Desktop/WorkSpace/CertusNet/oam_du/5gran/radisys-du/src/du_app/oam_agent/yang/cell -p /usr/local/confd/src/confd/yang -o ~/Desktop/WorkSpace/111.xsl
#python pyang.py -f pathheader /home/guoliang/Desktop/WorkSpace/CertusNet/oam_du/5gran/radisys-du/src/du_app/oam_agent/yang/cell/certus-5gnr-du-cells@2019-06-20.yang -p /home/guoliang/Desktop/WorkSpace/CertusNet/oam_du/5gran/radisys-du/src/du_app/oam_agent/yang/cell -p /usr/local/confd/src/confd/yang -o ~/Desktop/WorkSpace/111.tree


python pyang.py -f xtypedef /home/guoliang/Desktop/WorkSpace/CertusNet/oam_du/5gran/radisys-du/src/du_app/oam_agent/yang/cell/certus-5gnr-du-cell-base-cfg@2019-06-20.yang -p /home/guoliang/Desktop/WorkSpace/CertusNet/oam_du/5gran/radisys-du/src/du_app/oam_agent/yang/cell -p /usr/local/confd/src/confd/yang -o ~/Desktop/WorkSpace/CertusNet/GenConfD/certus_5gnr_du_cell_base_cfg.h
python pyang.py -f xtypedef /home/guoliang/Desktop/WorkSpace/CertusNet/oam_du/5gran/radisys-du/src/du_app/oam_agent/yang/cell/certus-5gnr-du-cell-channel-cfg@2019-06-20.yang -p /home/guoliang/Desktop/WorkSpace/CertusNet/oam_du/5gran/radisys-du/src/du_app/oam_agent/yang/cell -p /usr/local/confd/src/confd/yang -o ~/Desktop/WorkSpace/CertusNet/GenConfD/certus_5gnr_du_cell_channel_cfg.h
python pyang.py -f xtypedef /home/guoliang/Desktop/WorkSpace/CertusNet/oam_du/5gran/radisys-du/src/du_app/oam_agent/yang/cell/certus-5gnr-du-cell-l1-cfg@2019-06-20.yang -p /home/guoliang/Desktop/WorkSpace/CertusNet/oam_du/5gran/radisys-du/src/du_app/oam_agent/yang/cell -p /usr/local/confd/src/confd/yang -o ~/Desktop/WorkSpace/CertusNet/GenConfD/certus_5gnr_du_cell_l1_cfg.h
python pyang.py -f xtypedef /home/guoliang/Desktop/WorkSpace/CertusNet/oam_du/5gran/radisys-du/src/du_app/oam_agent/yang/cell/certus-5gnr-du-cell-schd-cfg@2019-06-20.yang -p /home/guoliang/Desktop/WorkSpace/CertusNet/oam_du/5gran/radisys-du/src/du_app/oam_agent/yang/cell -p /usr/local/confd/src/confd/yang -o ~/Desktop/WorkSpace/CertusNet/GenConfD/certus_5gnr_du_cell_schd_cfg.h